Add full pantheon build actions
alleyinteractive/create-wordpress-project pull request #28
Opened 2023-07-07 19:45 UTC by srtfisher

2023-07-10 13:14 UTC, renatonascalves approved these changes
🌵

2023-07-11 10:06 UTC, kevinfodness requested changes

2023-07-11 10:06 UTC, kevinfodness commented on .deployignore
> +vendor
Is this correct? Would we want to install Composer dependencies used in production on Pantheon in a `vendor` folder? I know that for VIP we put this in `client-mu-plugins` but on Pantheon we may want to just use the standard `vendor` folder.

2023-07-11 10:06 UTC, kevinfodness commented on .pantheon/pantheon.yml
> +  - /wp-content/vendor
We're expecting the vendor path to live here, so we shouldn't be deployignoring it.

2023-07-11 10:06 UTC, kevinfodness commented on .pantheon/pantheon.yml
> +  - /wp-content/.phpcs.xml
Alternately, could we deployignore development files like these so they don't make it to Pantheon's systems at all? We could do the same with test folders, and even with source folders that are transpiled (e.g., include the `build` folder in the plugin, but not the `blocks` or `entries` folder).

2023-07-11 10:06 UTC, kevinfodness commented on .pantheon/pantheon.yml
> +php_version: 8.1
If we're going to use 8.1 here we ought to use it in this project as a whole. Could you set this to 8.0 for now and file an issue to bump the repo to 8.1? We'll need to update composer.json and rebuild the lockfile.

2023-07-11 10:06 UTC, kevinfodness commented on ci-templates/.github/workflows/deploy-to-pantheon-live.yml
> +        submodules: 'recursive'
I'd really love to kill submodules for good. Composer is a better method for installing dependencies.

2023-07-11 10:06 UTC, kevinfodness commented on ci-templates/.github/workflows/deploy-to-pantheon-live.yml
> +        node-version: 16
This project uses node 18 so we'll need to reflect that everywhere.

2023-07-11 10:06 UTC, kevinfodness commented on ci-templates/.github/workflows/deploy-to-pantheon-live.yml
> +    # - name: Cache Theme Webpack Folder
Why is this commented out?

2023-07-11 10:06 UTC, kevinfodness commented on ci-templates/.github/workflows/deploy-to-pantheon-live.yml
> +        php-version: 8.1
Same comment here re: PHP version.

2023-07-11 10:06 UTC, kevinfodness commented on ci-templates/.github/workflows/deploy-to-pantheon-live.yml
> +      uses: alleyinteractive/action-deploy-to-remote-repository@feature # TODO: Update before merging
This is merged now.

2023-07-11 10:23 UTC, kevinfodness commented on .pantheon/pantheon.yml
> +php_version: 8.1
Alternately, we could go directly to 8.2. It's available on Pantheon and recommended.

2023-07-12 15:05 UTC, kevinfodness commented on ci-templates/.github/workflows/deploy-to-pantheon-multisite.yml
> +        remote_branch: 'staging'
We should make this dynamic based on the branch name that triggered the workflow. Recommendation:
```suggestion
        remote_branch: ${{ github.ref_name }}
```

2023-07-17 19:42 UTC, kevinfodness commented
See also #30

2023-07-19 15:29 UTC, kevinfodness commented
Rolled up into #30 - further modifications can be made in a followup feature branch / PR as necessary

2023-07-19 15:29 UTC, closed without merging